### ISSUE TITLE
tomcat7 deployment won't work on RHEL 6

### ISSUE THREAD

**Issue by predicador37** [lbetz/puppet-tomcat#9]
I'm having a new and weird problem with tomcat7 deployment on rhel/centos6. I'm testing a configuration on a pair of rhel machines. This configuration worked before. Now, I've got a lot of errors:

```
    [Notice: /Stage[main]/Profile::Apache_tomcat/Tomcat::Server[data]/Tomcat::Server::Install[data]/Exec[change provider in /etc/init.d/tomcat-data]: DependencyFile[/etc/init.d/tomcat-data] has failures: true]

    [Debug: /Stage[main]/Tomcat/File[/etc/sysconfig/tomcat]: Nothing to manage: no ensure and the resource doesn't exist
```

I'm trying a multi-instance configuration with a service called 'data'. Also, no tomcat7 package is installed...

Any ideas?

**Comment by lbetz** [comment]
Please send me your puppet code.

**Comment by predicador37** [comment]
Sure. This is the hiera data:

```
    tomcat::ensure: 'stopped'
    tomcat::enable: false
    tomcat::version: '7'
    tomcat_server:
      data:
        ensure: 'running'
        enable: true
        port: '8104'
        setenv:
          - 'ADD_JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses"'
        services:
          Catalina:
            connectors:
              http-8084:
                port: '8084'
                protocol: 'HTTP/1.1'
              ajp-8014:
                port: '8014'
                protocol: 'AJP/1.3'
        listeners:
           org.apache.catalina.core.AprLifecycleListener:
              ssl_engine: 'On'
           org.apache.catalina.core.JasperListener: {}
           org.apache.catalina.core.JreMemoryLeakPreventionListener: {}
           org.apache.catalina.mbeans.GlobalResourcesLifecycleListener: {}
           org.apache.catalina.core.ThreadLocalLeakPreventionListener: {}
      metadata:
        ensure: 'running'
        port: '8105'
        setenv:
          - 'ADD_JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses"'
        services:
          Catalina:
            connectors:
              http-8085:
                port: '8085'
                protocol: 'HTTP/1.1'
              ajp-8015:
                port: '8015'
                protocol: 'AJP/1.3'
        listeners:
           org.apache.catalina.core.AprLifecycleListener:
              ssl_engine: 'On'
           org.apache.catalina.core.JasperListener: {}
           org.apache.catalina.core.JreMemoryLeakPreventionListener: {}
           org.apache.catalina.mbeans.GlobalResourcesLifecycleListener: {}
           org.apache.catalina.core.ThreadLocalLeakPreventionListener: {}
```

Then I have a role-profile architecture. Relevant code that has to do with Tomcat:

```
class profile::apache_tomcat {
require tomcat
$tomcat_server = hiera('tomcat_server', {})
create_resources('tomcat::server', $tomcat_server)
}
```

And:

```
class role::appserver inherits role {

class{'profile::rhel':} ->
class{'profile::jdk':} ->
class{'profile::apache_tomcat':}
}
```

Profiles rhel and jdk contains EPEL repository and java open-jdk-1.7 respectively.
